{% set name = "jupyter-packaging" %}
{% set version = "0.7.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ded75723372e5ced2e1be1ee85506c88895518892f20eacc3b3a344cf59ce3a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - setuptools

test:
  imports:
    - jupyter_packaging

about:
  home: https://github.com/jupyter/jupyter-packaging
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Packaging Utilities

  description: |
    Jupyter Packaging Utilities
  dev_url: https://github.com/jupyter/jupyter-packaging

extra:
  recipe-maintainers:
    - blink1073
    - vidartf
    - timkpaine
