{% set name = "jupyter-packaging" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40e0555e5524f8e38839d17a6b007307713693d8ba20ec78829e497cd583a7d3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - setuptools

test:
  imports:
    - jupyter_packaging

about:
  home: https://github.com/jupyter/jupyter-packaging
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Packaging Utilities

  description: |
    Jupyter Packaging Utilities
  dev_url: https://github.com/jupyter/jupyter-packaging

extra:
  recipe-maintainers:
    - blink1073
    - vidartf
    - timkpaine
